### PR TITLE
Verbose logging minor tasks: add timing to verbose logs

### LINKED ISSUE #332: logger.info produces double output
@habanoz Using cb022b3a9e4

logger.debug() does not seem to be affected by this, only logger.info().
Additionally, this issue only happens after init() is called. If you add a simply logger.info("HELLO") before init() in main.py, this issue is not seen. Add the same line after init() and you'll see duplicate.

```
$ python3 src/main.py -f pymnt/cfg/ -r pymnt/reports/ -E /opt/tezos_mainnet/tezos -A 127.0.0.1:8732 -P rpc -M 3 -O 300 -C 296 -V on -D
...
...
2020-11-30 04:40:06,225 - MainThread - --------------------------------------------
--------------------------------------------
2020-11-30 04:40:06,226 - MainThread - BAKING ADDRESS is tz1asdfasffa
BAKING ADDRESS is tz1asdfasffa
2020-11-30 04:40:06,226 - MainThread - PAYMENT ADDRESS is backup
PAYMENT ADDRESS is backup
2020-11-30 04:40:06,226 - MainThread - --------------------------------------------
--------------------------------------------
2020-11-30 04:40:06,227 - MainThread - [Plugins] Loaded plugin Telegram
[Plugins] Loaded plugin Telegram
```

### PR DESCRIPTION
**Pull request by habanoz**
- Further tests resolved #332.
- Formatting change for the verbose logger to show time in log statements.  

**Work effort**: 1H

### CODE REVIEW

**Comment by jdsika** [comment]
Cool, there is a "draft mode" now! I will try it. Just set on PR and add a reviewer when you are finished

**Comment by jdsika** [comment]
@habanoz can we finish this one up? I am getting nervous if PRs stay open too long. Merge and move fast is the motto :D

**Comment by habanoz** [comment]
> @habanoz can we finish this one up? I am getting nervous if PRs stay open too long. Merge and move fast is the motto :D

I do not remember why this one is left unmerged.

**Comment by jdsika** [comment]
I don't know as well - you left it as WIP. Please think about it and set it ready for review.

**Comment by jdsika** [comment]
@utdrmac as your issue is linked here you have to test the fix and mark your issue as resolved, please

**Review by utdrmac — APPROVED** [review]

**Pull request merged**
