### PR TITLE
Replace travis with gh-actions

### PR DESCRIPTION
**Pull request by vkresch**
Replaced travis with gh actions
Travis CI replacement since it got a limit on open source project

---
No issue opened. The following steps were performed:

* **Analysis**: Travis CI charges open source projects after a usage of around 1000 minutes since last year.

* **Solution**: Move away from travis to github actions because github actions is free for open source projects. For more see [here](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/#:~:text=We%20want%20every%20open%20source,as%2Dyou%2Dgo%20pricing.) and [here](https://github.com/pricing). 

* **Implementation**: The workflow *.yml files were inspired by the [pybind11](https://github.com/pybind/pybind11) project.

* **Performed tests**: I performed simple tests on my [private repository](https://github.com/vkresch/actions-test) which generated [this](https://vkresch.github.io/actions-test/) documentation with the appropriate badges.

* **Documentation**: Updated the badge reference in the docs/index.rst, in the pull_request_template.md and the readme.md.

* **Further Suggestions**:
    - using [black](https://github.com/psf/black) formatter to use `black --check src/ tests/`
    - using [dependabot](https://dependabot.com/python/) which will open PRs when external dependencies change
    - extending the os test for windows and macOS
    - latexmk can be used to build a pdf out of the documentation which can be shared as an artifact through gh-actions

* **Check list**:

- [x] I extended the Travis CI test units with the corresponding tests for this new feature (if needed).
- [x] I extended the Sphinx documentation (if needed).
- [ ] I extended the help section (if needed).
- [x] I changed the README file (if needed).
- [ ] I created a new issue if there is further work left to be done (if needed).

**Work effort**: ~3h
+1h (added by @jdsika for long onboarding telephone calls)

### CODE REVIEW

**Comment by jdsika** [comment]
I like the suggestions for the next PR!

**Review by jdsika — APPROVED** [review]
LGTM, waiting for second approval

**Comment by jdsika** [comment]
@utdrmac, @habanoz and @amzid - look at this perfect example of documenting a PR. The "product owner" is very happy :D

**Comment by habanoz** [comment]
Thanks for the good work!

**Pull request merged**
