### PR TITLE
Unbreak and improve Docker image

### PR DESCRIPTION
**Pull request by Pea-skillz**
+ Update fysom to 2.1.6 to unbreak python 3.10
+ Pin python image used in Dockerfile
+ Add an unprivileged user to run trd

Fix issue https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/issues/543

Signed-off-by: Pierre-Emmanuel Andre <pierre-emmanuel.andre@skillz.io>

### CODE REVIEW

**Review by vkresch — DISMISSED** [review]
Looks good! Thanks for the PR. I tested it locally and it worked.

Things I noticed for another PR (opened issue [here](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/issues/546)).
- I think it would be good to have also a .dockerignore to ignore folders like .git and tests to keep the image/container smaller
- Reorder when to copy the source code and the requirements.txt for better cache usage of the docker build command

Review Effort: 0.5h

**Comment by jdsika** [comment]
@Pea-skillz have you been compensated by any work arrangement to create this contribution? If not you are entitled to a compensation through the TF grant that has been awarded to contributions to TRD. The contributors add their tz address and GitHub name to the contributors.csv in the repo and you note the amount of hours you have spend on this piece of work.

**Comment by Pea-skillz** [comment]
Hello,
Thanks for the review :) I have updated the `contributors.csv` file too.
Estimated effort to fix the Docker image: 1.5h
Regards,

**Review by jdsika — APPROVED** [review]

**Comment by jdsika** [comment]
@Pea-skillz congratulations to your first PR

**Pull request merged**
