### PR TITLE
Adjust staking balance when snapshot index == 15

### LINKED ISSUE #239: Calculate correct staking balance when snapshot index = 15
RE: https://medium.com/@_MisterWalker_/we-all-were-wrong-baking-bad-and-most-bakers-were-using-wrong-data-to-calculate-staking-rewards-a8c26f5ec62b

```
just to clarify the logic:
  - when snapshotIndex < 15, realStakingBalance = staking_balance
  - when snapshotIndex == 15, realStakingBalance = (staking_balance - metadataUnfrozenRewards)
```

### PR DESCRIPTION
**Pull request by utdrmac**
Closes #239

### CODE REVIEW

**Comment by utdrmac** [comment]
- Need to test this against more cycle rewards where snapshot index == 15.
- Need to verify `old_rewards_cycle` math works against carthagenet

**Comment by jdsika** [comment]
@utdrmac it is better you create branches as discussed for @amzid to be able to apply changes. I suggest you open this as a branch and add the PR template as I asked amzid to investigate your todos:


>     Need to test this against more cycle rewards where snapshot index == 15.
>     Need to verify old_rewards_cycle math works against carthagenet

**Comment by utdrmac** [comment]
@jdsika It is a branch, `issue_239` or you mean a branch on the main TRD repo?

**Comment by utdrmac** [comment]
Will reopen with PR template

**Pull request closed without merging**
