### PR TITLE
Release: Prepare payments for FLORENCE release, EDO has been skipped

### PR DESCRIPTION
**Pull request by jdsika**
* **Check list**:

- [x] I calculated payments for all PRs.
- [x] I posted a payment summary and payments are done. -> I will release and repost the summary in the next PR adding the TX hashes
- [x] I wrote the changelog and release file.
- [x] I wrote the agora article for the community and updated the link in the release logs.
- [x] I searched and replaced all version numbers in the code.
- [x] Updated copyright information

**Work effort**:
jdsika, Effort=4h
dansan566, Effort=0.5h

### CODE REVIEW

**Comment by jdsika** [comment]
@vkresch build failed with 0 warnings :D

**Comment by amzid** [comment]
> @vkresch build failed with 0 warnings :D

The same behavior occurs in #448 too! I guess there is a broken dependency or version mismatch while building the documentation!

image

**Comment by vkresch** [comment]
@jdsika @amzid I'll take a look today.

**Comment by vkresch** [comment]
I created a hotfix https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/pull/451.

**Comment by jdsika** [comment]
@nicolasochem can you please add your tz address here (quickly) as I see a 1h work effort for docker in the logs and I am preparing for release payouts. Thank you!

**Comment by jdsika** [comment]
@dansan566 VWAP from 2021/07/19 please

**Comment by dansan566** [comment]
> @dansan566 VWAP from 2021/07/19 please

**2021-07-19      2.364659**

**Comment by sebuhbitcoin** [comment]
Hi my bakers address:

tz1R664EP6wjcM1RSUVJ7nrJisTpBW9QyJzP

**Comment by jdsika** [comment]
@utdrmac can we proceed as always and you generate the payments? We have a little too less XTZ in the contract. How do you suggest should we proceed?

Receiver | Amount in XTZ
-- | --
habanoz | 1347.97
jdsika | 626.41
amzid | 581.48
dansan566 | 520.69
denver-s | 132.15
sebuhbitcoin | 5.29
utdrmac | 555.05
vkresch | 917.15
  | 4686.19

**Comment by jdsika** [comment]
> 
> 
> Hi my bakers address:
> 
> tz1R664EP6wjcM1RSUVJ7nrJisTpBW9QyJzP

So you will receive your developer donations to this address?

**Review by dansan566 — APPROVED** [review]

**Review by utdrmac — APPROVED** [review]

**Review by dansan566 — APPROVED** [review]

**Pull request merged**
