### PR TITLE
fix #678 - Fix single-shot mode always exiting in error

### LINKED ISSUE #678: TRD exiting with status code 1, even when it succeeds
**Describe the bug**
New exit code handling added in [this pr](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/pull/657) appear to make TRD always exit with `1`, ie: failure.

**Environment**
 - k8s running the v17.2 tezos dockerhub image, with the TRD repo v11.1 release 

## Scenario 1: payments have already been made
```
023-08-01 16:10:24,456 - MainThread - INFO - [Plugins] No plugins enabled
2023-08-01 16:10:24,457 - MainThread - INFO - Initial cycle set to -1
2023-08-01 16:10:24,459 - MainThread - INFO - Application is READY!
2023-08-01 16:10:24,459 - MainThread - INFO - --------------------------------------------
2023-08-01 16:10:38,594 - producer  - INFO - Checking for pending payments: checking 635 <= 636 - 1 - 0
2023-08-01 16:10:38,594 - producer  - INFO - Payment cycle is 635
2023-08-01 16:10:38,594 - producer  - WARNING - Payment report for cycle 635 is present. No payment will be run for the cycle. Check '/home/tezos/pymnt/reports/.../payments/done/635.csv'
2023-08-01 16:10:38,595 - producer  - INFO - Run mode ONETIME satisfied. Terminating...
2023-08-01 16:10:38,595 - producer  - INFO - Sending KeyboardInterrupt signal.
2023-08-01 16:10:38,595 - consumer0 - WARNING - Exit signal received. Terminating...
2023-08-01 16:10:38,595 - producer  - INFO - Error at payment producer. Please consult the verbose logs! Exit code: 0
2023-08-01 16:10:44,476 - MainThread - INFO - Interrupted.
2023-08-01 16:10:44,477 - MainThread - INFO - TRD is shutting down...
2023-08-01 16:10:44,477 - MainThread - INFO - --------------------------------------------------------
2023-08-01 16:10:44,477 - MainThread - INFO - Sensitive operations are in progress!
2023-08-01 16:10:44,477 - MainThread - INFO - Please wait while the application is being shut down!
2023-08-01 16:10:44,477 - MainThread - INFO - --------------------------------------------------------
2023-08-01 16:10:44,478 - MainThread - INFO - Lock file removed!
2023-08-01 16:10:44,478 - MainThread - INFO - Shutdown due to error! Exit code: 1
```

notice the `producer` thread has the exit code 0 (success), and no errors are logged in either the primary or verbose logs. But it appears this bit of code always sends a `KeyboardInterrupt` signal, and that signal always causes the app to exit with an error even when no error is present:

https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/blob/277cbb2c3f49e9b6d9d7951c97a138793279e613/src/pay/payment_producer.py#L141-L157

https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/blob/dd3378b40833b6a7bf66e926fea45cb714f88cec/src/util/process_life_cycle.py#L229-L231

## Scenario 2: Payments haven't yet been made
```
2023-08-01 16:01:03,244 - consumer0 - INFO - Payment of batch 1 started
2023-08-01 16:01:06,709 - consumer0 - INFO - minimal required fee is 108645, current used fee is 163900
2023-08-01 16:01:06,971 - producer  - INFO - Reward creation is done for cycle 635, created 3269 rewards.
2023-08-01 16:01:06,971 - producer  - INFO - Run mode ONETIME satisfied. Terminating...
2023-08-01 16:01:06,971 - producer  - INFO - Sending KeyboardInterrupt signal.
2023-08-01 16:01:06,971 - producer  - INFO - Error at payment producer. Please consult the verbose logs! Exit code: 0
2023-08-01 16:01:09,825 - consumer0 - INFO - Operation hash is ...
2023-08-01 16:01:09,826 - consumer0 - INFO - Waiting for operation ... to be included... Please do not interrupt the process! (Timeout is around 150 minutes)
2023-08-01 16:01:10,203 - MainThread - INFO - Interrupted.
2023-08-01 16:01:10,203 - MainThread - INFO - TRD is shutting down...
2023-08-01 16:01:10,203 - MainThread - INFO - --------------------------------------------------------
2023-08-01 16:01:10,203 - MainThread - INFO - Sensitive operations are in progress!
2023-08-01 16:01:10,203 - MainThread - INFO - Please wait while the application is being shut down!
2023-08-01 16:01:10,204 - MainThread - INFO - --------------------------------------------------------
2023-08-01 16:01:10,204 - MainThread - INFO - Lock file removed!
2023-08-01 16:01:10,204 - MainThread - INFO - Shutdown due to error! Exit code: 1
...
2023-08-01 16:05:59,367 - consumer0 - INFO - Payment of batch 11 succeeded in 1 attempt(s)
2023-08-01 16:05:59,369 - consumer0 - INFO - Processing completed for 2538 payment items.
2023-08-01 16:05:59,386 - consumer0 - INFO - Payment report is created at '/home/tezos/pymnt/reports/.../payments/done/635.csv'
2023-08-01 16:06:00,065 - consumer0 - INFO - Calculation report is created at '/home/tezos/pymnt/reports/.../calculations/635.csv'
2023-08-01 16:06:00,065 - consumer0 - INFO - Simulated transaction_fees added to calculations file.
2023-08-01 16:06:00,068 - consumer0 - INFO - [Plugins] Not sending notification; no plugins enabled
2023-08-01 16:06:00,068 - consumer0 - INFO - [Plugins] Not sending notification; no plugins enabled
2023-08-01 16:06:00,071 - consumer0 - INFO - Sending anonymous statistics; See docs/statistics.rst for more information.
2023-08-01 16:06:01,438 - consumer0 - WARNING - Exit signal received. Terminating...
```

Again we see the `producer` thread exits with a 0 (success) signal, but TRD still says "error". No errors appear in the regular or verbose logs. All payments go out as expected. TRD exits with a `1` (failure), so k8s tries to restart it to run again which is not necessary since it actually succeeded.

> 2023-08-01 16:01:06,971 - producer  - INFO - Error at payment producer. Please consult the verbose logs! Exit code: 0

This log line specifically is super confusing: it's an `INFO` level log, but says there is an `Error`, and the exit code is `0 (success)`

### PR DESCRIPTION
**Pull request by nicolasochem**
We added code in #653 to have TRD send a non-zero exit status when anything wrong happens - including payout failures, or (relevant here) keyboard interrupts.

However, it turns out that when using TRD in runmode -2, -3, -4, the regular course of operations is to have the producer thread send a KeyboardInterrupt when done... which is then treated as error!

This is done with `_thread.interrupt_main()`. It's bad: humans send interrupts, programs should not. Instead, I'm suggesting that the producer use `SIGUSR1` to trigger a normal interruption.

This triggers the same code path as today, just with an exit status of SUCCESS. So I expect that the main thread will still wait for the consumer, and it won't actually exit before payouts are done, if there are any.

This allows kubernetes bakers (for example) to use a k8s cronjob and get alerted automatically in case of payment failures.

For the record, I still believe this entire producer/consumer logic should be thrown away and we should simply do things in order (calculate, then pay). I've ranted about this before (#491).

**Work effort**: 3 hours

### CODE REVIEW

**Comment by nicolasochem** [comment]
@jmo-staked good catch! I just pushed a fix, can you please try again?

**Comment by nicolasochem** [comment]
yes I'm using two signals, SIGUSR1 indicates success and SIGUSR2 is failure... it's fine.

Does it return 0 when payout succeeds?

**Comment by nicolasochem** [comment]
> Might have hit one minor other exit error, in this case the `MainThread` exit code was logged incorrectly:
> 
> ```shell
> 2023-08-29 16:00:53,401 - MainThread - INFO - [Plugins] No plugins enabled
> 2023-08-29 16:00:53,402 - MainThread - INFO - Initial cycle set to -1
> 2023-08-29 16:00:53,411 - MainThread - INFO - Application is READY!
> 2023-08-29 16:00:53,411 - MainThread - INFO - --------------------------------------------
> 2023-08-29 16:00:54,489 - producer  - ERROR - Unable to fetch current cycle from provider tzkt, Not synced. Exiting.
> 2023-08-29 16:00:54,490 - consumer0 - WARNING - Exit signal received. Terminating...
> 2023-08-29 16:00:54,490 - producer  - INFO - TRD Exit triggered by producer Exit code: 8
> 2023-08-29 16:00:54,490 - MainThread - INFO - Application stop handler called by producer: 10
> 2023-08-29 16:00:54,491 - MainThread - INFO - TRD is shutting down...
> 2023-08-29 16:00:54,492 - MainThread - INFO - --------------------------------------------------------
> 2023-08-29 16:00:54,492 - MainThread - INFO - Sensitive operations are in progress!
> 2023-08-29 16:00:54,492 - MainThread - INFO - Please wait while the application is being shut down!
> 2023-08-29 16:00:54,492 - MainThread - INFO - --------------------------------------------------------
> 2023-08-29 16:00:54,492 - MainThread - INFO - Lock file removed!
> 2023-08-29 16:00:54,493 - MainThread - INFO - Shutdown. Exit code: 0
> ```
> 
> ```
> $ kubectl describe po ...
>     State:          Terminated
>       Reason:       Error
>       Exit Code:    1
> ```
> 
> `MainThread` reports it's exiting with code `0`, even though the app is exiting due to error, but the actual exit signal k8s sees is `1` which is good, so the job correctly restarted.


I don't think this is true. I think that actually, in case of tzkt unresponsive, the app exited succesfully, which is not what should happen. I have now modified the code to propagate producer errors (unresponsive tzkt, disk full etc)... to the main thread. @jmo-staked @jdsika could you please check urgently?

**Review by jdsika — APPROVED** [review]

**Comment by nicolasochem** [comment]
@jdsika pointed out that these signals are not available on windows, more work is needed

https://stackoverflow.com/questions/16429480/what-is-equivalent-to-sigusr1-2-signals-in-windows-using-python

**Pull request merged**
