### PR TITLE
Support all tezos curves

### PR DESCRIPTION
**Pull request by utdrmac**
Work Effort: 2hr

### CODE REVIEW

**Review by teddyknox — APPROVED** [review]
Thanks!!

**Comment by jdsika** [comment]
@teddyknox did you test the code?

**Comment by jdsika** [comment]
@utdrmac lint is failing now - how did you test it? Can't we unit test this?

**Comment by utdrmac** [comment]
> @utdrmac lint is failing now - how did you test it? Can't we unit test this?

I tested it with a standalone script. The issue with unit testing it is that you would need a revealed tz1/tz2/tz3 address on whichever chain you're testing against since the parent function makes an RPC call to fetch the public key.

**Pull request merged**
