### PR TITLE
Reactivate tests and remove dead code

### PR DESCRIPTION
**Pull request by vkresch**
- Reactivate and update tests and remove dead code
- Removing tzpro and rpc code
- Replacing depracted pkg_resource in python 3.12 with importlib.metadata:

> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.
Source: https://setuptools.pypa.io/en/latest/pkg_resources.html

- Depracate distutils for python 3.12 (Source: https://peps.python.org/pep-0632/)

**Work effort**: 8h
**Review time**: 1h (nochem)

### CODE REVIEW

**Comment by nicolasochem** [comment]
thank you for this @vkresch 

I see small changes in src/. I can test for cycle 751 payouts. Then we can merge this.

We can do a 13.1 release in a less rushed fashion. Anything else you'd like to do?

I am considering removing all code for `owner` and `founder` since it no longer makes sense in Paris protocol. See discussion on baking slack. Any thoughts on this? @vkresch @jdsika

**Comment by vkresch** [comment]
Thanks. During the test reactivation there were some Attribute not found errors of the PaymentProducer (for example self.exiting and self.payments_queue) so I moved the attribute definitions on top to avoid this. Please check the functionality on your side. 

> I am considering removing all code for owner and founder since it no longer makes sense in Paris protocol. See discussion on baking slack. Any thoughts on this? @vkresch @jdsika

I think it is good step to clean up and simplify the code base. I already liked the move to only Tzkt API.

**Review by nicolasochem — APPROVED** [review]
Thanks! It worked for me, I had to fix a few things for docker to work.

**Comment by vkresch** [comment]
> Thanks! It worked for me, I had to fix a few things for docker to work.

Thanks!

**Pull request merged**
