### PR TITLE
Adjust staking balance when snapshot index == 15

### PR DESCRIPTION
**Pull request by utdrmac**
This PR resolves the issue #239 . The following steps were performed:

* **Analysis**: BakingBad determined that the Tezos blockchain calculates an inconsistent balance when the snapshot index is 15. https://medium.com/@_MisterWalker_/we-all-were-wrong-baking-bad-and-most-bakers-were-using-wrong-data-to-calculate-staking-rewards-a8c26f5ec62b
* **Solution**: BakingBad's solution is to simply remove the unfrozen balance from calculations
* **Implementation**: If snapshot index is 15, fetch bakers balances and subtract unfrozen amounts from total before doing payouts calculations
* **Performed tests**: Adjusted code, then executed production payouts for C244 (snapshot 15)
* **Documentation**: Comments in code

* **Check list**:

[NA] I extended the Travis CI test units with the corresponding tests for this new feature (if needed).
[NA] I extended the Sphinx documentation (if needed).
[NA] I extended the help section (if needed).
[NA] I changed the README file (if needed).
[NA] I created a new issue if there is further work left to be done (if needed).

**Work effort**: 4 hours

### CODE REVIEW

**Comment by amzid** [comment]
Are you sure that the snapshot of C244 is at index 15? [TzKt](https://tzkt.io/cycles) says it is at index 7, or am I misunderstanding you?

**Comment by amzid** [comment]
Are you sure that the snapshot of C244 is at index 15? According to [TzKt](https://tzkt.io/cycles), I think it is at index 7

**Comment by utdrmac** [comment]
https://api.tzstats.com/explorer/cycle/244
Says snapshot_index 15

**Comment by amzid** [comment]
For the payouts of C 244, the snapshot cycle is C 237 with a snapshot index of 7.
For the payouts of C 251, the snapshot cycle is C 244 with a snapshot index of 15.
In my understanding, the test should be performed using -C 251. The tests deliver the desired results compared against tzkt.

**Review by amzid — APPROVED** [review]

**Pull request merged**
