### PR TITLE
Plugins Upgrade Notice

### PR DESCRIPTION
**Pull request by utdrmac**
force plugins to be validated on main.py startup to print easier to read error message

### CODE REVIEW

**Comment by utdrmac** [comment]
```
2020-11-12 02:04:37,555 - MainThread - [Plugins] Detected obsolete email config file. Please convert to the new plugins system. 'email.ini' renamed 'email.ini.old'
```

**Comment by habanoz** [comment]
> Detected obsolete email config file. Please convert to the new plugins system.

How can I do this? What is needed for conversion?

**Comment by habanoz** [comment]
@jdsika @utdrmac @amzid 

We have a requirements.txt file. Do we add new dependencies to the file?

**Comment by dansan566** [comment]
```
 Traceback (most recent call last):
  File "src/main.py", line 242, in <module>
    main(args)
  File "src/main.py", line 162, in main
    plugins_manager = plugins.PluginManager(cfg.get_plugins_conf(), args.verbose, dry_run)
  File "/Users/dl/tezos-reward-distributor/src/model/baking_conf.py", line 99, in get_plugins_conf
    return self.get_attribute(PLUGINS_CONF)
  File "/Users/dl/tezos-reward-distributor/src/model/baking_conf.py", line 45, in get_attribute
    raise Exception("Attribute {} not found in application configuration.".format(attr))
Exception: Attribute plugins not found in application configuration.
```

**Comment by dansan566** [comment]
I just checked the documentation. The link to the example config is broken! 
Bildschirmfoto 2020-11-12 um 09 23 59

**Comment by dansan566** [comment]
@utdrmac It fixes the error message! However, it wasn't easy to find the plugin section in the doc quickly. As mentioned in my other comment in the PR [#295,](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/pull/295) the link to the example config is broken.

**Comment by utdrmac** [comment]
@dansan566 This PR should fix your issues mentioned in #295

**Comment by utdrmac** [comment]
@habanoz I changed the message. Now reads this to tell you what to do.
```
[Plugins] Detected obsolete email config file. Please copy the settings from 'email.ini' to the new plugins system. 'email.ini' has renamed 'email.ini.old'")
```

**Review by jdsika — APPROVED** [review]

**Pull request merged**
