### PR TITLE
Better handling of telegram API errors

### LINKED ISSUE #469: Telegram plugin incorrectly parses result from API
*BIG EDIT*:
The telegram plugin does not appear to be checking the result of API calls. Basic logs indicate successful posting, but debug logs show failure. TRD should output proper error message.

```
2021-07-28 08:17:20,838 - consumer0 - DEBUG - [TelegramPlugin] Public Response: {'ok': False, 'error_code': 400, 'description': 'Bad Request: can\'t parse entities: Unsupported start tag "3" at byte offset 163'}
2021-07-28 08:17:20,839 - consumer0 - INFO - [TelegramPlugin] Public Notification 'Reward for cycle 384...' sent
```

### PR DESCRIPTION
**Pull request by utdrmac**
Fixes #469

@sebuhbitcoin please test

**Work effort**: 1hr

### CODE REVIEW

**Comment by sebuhbitcoin** [comment]
okay Ill test after this cycle is done. sometime tomorrow.

**Comment by sebuhbitcoin** [comment]
```
    telegram_text: >
      Reward for cycle %CYCLE% <b>complete</b>!
      We had %NDELEGATORS% <i>delegators</i> in the cycle and paid out %TREWARDS% XTZ in rewards!
      <3 <3 <3 Thank you for baking with The Sebuh Tezos Baker <3 <3 <3
```

This will be the subject of this test.

**Comment by sebuhbitcoin** [comment]
`2021-07-31 19:28:07,095 - consumer0 - INFO - [TelegramPlugin] Sent PAYOUT notification to chatId: -1001345449543
2021-07-31 19:28:07,097 - consumer0 - DEBUG - [TelegramPlugin] PAYOUT raw response: {'ok': False, 'error_code': 400, 'description': 'Bad Request: can\'t parse entities: Unsupported start tag "3" at byte offset 115'}
2021-07-31 19:28:07,097 - consumer0 - ERROR - [Plugins] [Telegram] Unknown Error: 'dict' object has no attribute 'ok'
2021-07-31 19:28:07,799 - consumer0 - INFO - [TelegramPlugin] Sent ADMIN notification to chatId: -1001462541233
2021-07-31 19:28:07,800 - consumer0 - DEBUG - [TelegramPlugin] ADMIN raw response: {'ok': True, 'result': {'message_id': 67444, 'from': {'id': 1824410105, 'is_bot': True, 'first_name': 'Sebuh.net Payouts Notifier', 'username': 'Sebuh_Payout_bot'}, 'chat': {'id': -1001462541233, 'title': 'Sebuh Squad - Secret Chat', 'type': 'supergroup'}, 'date': 1627784887, 'text': 'Reward Payouts for Cycle 385 Completed Successfully!\nThe current payout account balance is expected to last for the next 3 cycle(s)!', 'entities': [{'offset': 0, 'length': 52, 'type': 'bold'}]}}
2021-07-31 19:28:07,800 - consumer0 - ERROR - [Plugins] [Telegram] Unknown Error: 'dict' object has no attribute 'ok'`

This is the results I received from the APP_Verbose log for my cycle 385 Payment.
The Telegram message that contained <3 in it meant for the @sebuh_net_chat room was not sent and this error was created. 

In the TRD payment command closing statement seen was this. 
`2021-07-31 19:28:07,095 - consumer0 - INFO - [TelegramPlugin] Sent PAYOUT notification to chatId: -1001345449543
2021-07-31 19:28:07,097 - consumer0 - ERROR - [Plugins] [Telegram] Unknown Error: 'dict' object has no attribute 'ok'
2021-07-31 19:28:07,799 - consumer0 - INFO - [TelegramPlugin] Sent ADMIN notification to chatId: -1001462541233
2021-07-31 19:28:07,800 - consumer0 - ERROR - [Plugins] [Telegram] Unknown Error: 'dict' object has no attribute 'ok'
`

**Comment by utdrmac** [comment]
@sebuhbitcoin Ugh. Sorry. I applied a minor correction. It should be `respJ["ok"]`. Please pull the latest PR code and check again?

**Comment by sebuhbitcoin** [comment]
Ill git pull the PR on cycle 386 and test again and report my findings.

**Review by jdsika — APPROVED** [review]

**Comment by jdsika** [comment]
@sebuhbitcoin please add your tz address in a PR to the contributors file

**Pull request merged**
