### PR TITLE
CI: fix build-documentation warnings

### PR DESCRIPTION
**Pull request by denver-s**
---
name: CI: fix build-documentation warnings
about: Resolve some documentations warnings.
labels: 

---
IMPORTANT NOTICE:
I read and understood the [guidelines for contributions to the TRD](https://tezos-reward-distributor-organization.github.io/tezos-reward-distributor/contributors.html). The contribution may qualify for being compensated by the TRD grant if approved by the maintainers.

* **Analysis**: See that CI warns about some linting errors (e.g. section "Unchanged files with check annotations" at https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/pull/457/files)

* **Check list**:

- [x] I extended the Github Actions CI test units with the corresponding tests for this new feature (if needed).
- [x] I extended the Sphinx documentation (if needed).
- [x] I extended the help section (if needed).
- [x] I changed the README file (if needed).
- [x] I created a new issue if there is further work left to be done (if needed).

**Work effort**: 10 minutes. (@jdsika remembers and will do this with effort 0h for simplicity)

### CODE REVIEW

**Comment by jdsika** [comment]
I already fixed this in #450 but we will just merge this first.

**Review by jdsika — APPROVED** [review]

**Comment by denver-s** [comment]
> I already fixed this in #450 but we will just merge this first.

Sorry! I did not see it.

**Comment by jdsika** [comment]
If you allow I will remember the 10min effort for another PR to keep make tha calculations on payments a bit easier :D

**Comment by denver-s** [comment]
> If you allow I will remember the 10min effort for another PR to keep make tha calculations on payments a bit easier :D

Sure, no problem.

**Pull request merged**
