### PR TITLE
[WIP] Added plugins subsystem

### PR DESCRIPTION
**Pull request by utdrmac**
- email plugin replaces email_manager/email_worker
- telegram, webhook, twitter all working plugins
- modifications to consumer and batch_payer to use plugins for notifications

* **Check list**:

[ ] I extended the Travis CI test units with the corresponding tests for this new feature (if needed).

[X] I extended the Sphinx documentation (if needed).

[NA] I extended the help section (if needed).

[NA] I changed the README file (if needed).

**Work effort**: 24hrs

### CODE REVIEW

**Comment by utdrmac** [comment]
I still need to add some unit tests to make sure the yaml parses correctly

**Comment by jdsika** [comment]
This is VERY cool @dansan566

**Comment by utdrmac** [comment]
I tried to write just a few "basic" plugins as examples. This way, if anyone else wants to write one for Slack, or Facebook, or reddit, etc, they can just follow the model.

**Comment by jdsika** [comment]
@utdrmac what should be the process to signal others that the PR is "ready for review"?
1) Remove [WIP] in the title
2) Add desired reviewer
3) add Label "ready for review"
4) (Additionally ping person in conversation)

?

**Comment by utdrmac** [comment]
1. Yes
2. Yes
3. Probably should have a label "WIP" initially? Then when ready, remove that one, then add "needs review" tag?
4. Sure

**Review by habanoz — APPROVED** [review]
I have made a quick review. Thanks for docs update.

**Comment by habanoz** [comment]
Merging ...

**Comment by habanoz** [comment]
Leaving the plugins branch.

**Comment by dansan566** [comment]
```
 Traceback (most recent call last):
  File "src/main.py", line 242, in <module>
    main(args)
  File "src/main.py", line 162, in main
    plugins_manager = plugins.PluginManager(cfg.get_plugins_conf(), args.verbose, dry_run)
  File "/Users/dl/tezos-reward-distributor/src/model/baking_conf.py", line 99, in get_plugins_conf
    return self.get_attribute(PLUGINS_CONF)
  File "/Users/dl/tezos-reward-distributor/src/model/baking_conf.py", line 45, in get_attribute
    raise Exception("Attribute {} not found in application configuration.".format(attr))
Exception: Attribute plugins not found in application configuration.
```

**Comment by dansan566** [comment]
I just checked the documentation. The link to the example config is broken! 
Bildschirmfoto 2020-11-12 um 09 23 59

**Pull request merged**
