### PR TITLE
Setup scripts

### PR DESCRIPTION
**Pull request by denver-s**
---
name: Scripts to setup and update TRD
about: Make it easier to users and developers
labels: 

---
IMPORTANT NOTICE:
I read and understood the [guidelines for contributions to the TRD](https://tezos-reward-distributor-organization.github.io/tezos-reward-distributor/contributors.html). The contribution may qualify for being compensated by the TRD grant if approved by the maintainers.

The following steps were performed:

* **Analysis**: It is quite annoying to type many command lines just to regularly update, and there are no guidelines on what to install to become a developer or tester.

* **Solution**: Make those commands as executable bash scripts.

* **Implementation**: Add a folder `scripts/` that includes bash scripts that make those operations easy and maintainable. CI is also using it in `build-trd` job.

* **Performed tests**: Tried running the scripts (from different paths).

* **Documentation**: Updated readme.

* **Check list**:

- [x] I extended the Github Actions CI test units with the corresponding tests for this new feature (if needed).
- [x] I extended the Sphinx documentation (if needed).
- [x] I extended the help section (if needed).
- [x] I changed the README file (if needed).
- [x] I created a new issue if there is further work left to be done (if needed).

**Work effort**: 1 hour.

### CODE REVIEW

**Comment by jdsika** [comment]
The only annoying thing here is that often on windows machines you have `python` as command instead of `python3`. It would be elegant if the script checks for both commands and which one returns with `--version` the version 3.6 and use that one. What do you think?

**Comment by denver-s** [comment]
@jdsika I was thinking about the same, regarding `python3`. I don't like it, and also `python` shuold be a symlink to the most recent Python version installed on the machine. I'm in favor of using `python`

**Comment by denver-s** [comment]
BTW, most of documentation (and readme) have always cited python3 and not python.

**Comment by jdsika** [comment]
@denver-s should the script check if it is on master branch? because while testing it on this branch it does just update the branch it is currently on

**Comment by dansan566** [comment]
Run it with Mac OS, got some info from the output:
`sudo: apt-get: command not found`
and
`DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621`
Last line from the output:
`Successfully installed attrs-21.2.0 flake8-3.9.2 graphviz-0.17 iniconfig-1.1.1 mccabe-0.6.1 packaging-21.0 parameterized-0.8.1 pluggy-0.13.1 py-1.10.0 pycodestyle-2.7.0 pyflakes-2.3.1 pyparsing-2.4.7 pytest-6.2.4 toml-0.10.2
`

**Comment by denver-s** [comment]
> Run it with Mac OS, got some info from the output:
> `sudo: apt-get: command not found`

Maybe `sudo apt` is a better choice?

**Comment by denver-s** [comment]
> @denver-s should the script check if it is on master branch? because while testing it on this branch it does just update the branch it is currently on

I think that if one know how to switch between branches, then they are probably "advanced" users. Furthermore, we recently saw that with the Granada branch, people had to update that branch in order to test the fixes.

**Comment by denver-s** [comment]
We probably need to clarify which platform TRD officially supports.

If we want to support Linux, WSL2, Cygwin, macOS, we need to test and eventually create a script to detect which OS it is running on. Taken from [StackOverflow](https://stackoverflow.com/questions/3466166/how-to-check-if-running-in-cygwin-mac-or-linux#17072017):

```
#!/usr/bin/env bash

if [ "$(uname)" == "Darwin" ]; then
    # Do something under Mac OS X platform        
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    # Do something under GNU/Linux platform
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
    # Do something under 32 bits Windows NT platform
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
    # Do something under 64 bits Windows NT platform
fi
```

**Comment by ericlavoie** [comment]
The readme changes contains part of the info from #516 in providing the link for support and opening an issue. Can we push that change in a separate branch and merge it?

**Comment by jdsika** [comment]
@denver-s what is your timeline? We need to push a little forward due to the upcoming tendermint changes

**Comment by jdsika** [comment]
@denver-s I will close this PR due to inactivity if there is no response soon, ok?

**Comment by denver-s** [comment]
Yes, sorry but it's not the right time for me to work on this.

**Pull request closed without merging**
