### PR TITLE
application launch states diagram added.

### PR DESCRIPTION
**Pull request by habanoz**
---
name: Pull Request
about: Create a pull request to make a contribution
labels: 

---
IMPORTANT NOTICE:
I read and understood the [guidelines for contributions to the TRD](https://tezos-reward-distributor-organization.github.io/tezos-reward-distributor/contributors.html). The contribution may qualify for being compensated by the TRD grant if approved by the maintainers.

This PR resolves the issue <Not determined>. The following steps were performed:

**Work effort**: 6.5 H

### CODE REVIEW

**Comment by habanoz** [comment]
Payment Producer process and Create Payment sub-process added.

**Comment by habanoz** [comment]
Payment Consumers Diagrams Added: 
- Payment Consumer States Diagram
- Batch Payer States Diagram
- Attempt Payment States Diagram 
- Payment Operation States Diagram

**Comment by habanoz** [comment]
TODO: Add uniquely enumerated names to all state diagrams, eg. DIAGRAM 1.1 PAYMENT CONSUMER DIAGRAM
TODO: Standardize notations
TODO: Improve notation for call states

**Comment by amzid** [comment]
I think the block "pay the items" under "comsumer_states_diagram_1.0.pdf" needs to be refined, since it is the most critical stage. Many scenarios are possible here: one single payment item is skipped (different states for skipping reason?), one payment batch is timing out (this is critical because if this impacts the counter so that all subsequent transactions fail as well if the inclusion takes longer than the TRD timeout), one payment batch failed. Otherwise, this can be part of a different issue/PR if I am misunderstanding the purpose of this PR.

**Comment by habanoz** [comment]
> I think the block "pay the items" under "comsumer_states_diagram_1.0.pdf" needs to be refined, since it is the most critical stage. Many scenarios are possible here: one single payment item is skipped (different states for skipping reason?), 

In the consumer states diagram, we show how the consumer works. Each payment item has its own state, we can not integrate it with the consumer flow. 

We may argue if we should modify payment items such that they include their own fsm.

> one payment batch is timing out (this is critical because if this impacts the counter so that all subsequent transactions fail as well if the inclusion takes longer than the TRD timeout), one payment batch failed. 

Batch timeout and failure is mentioned in the "Payment Operation States Diagram". 

Please see the last page of:

https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/blob/11b32ed2475549d51a155630056f2dd49ab27871/docs/fsm/comsumer_states_diagram_1.0.pdf 

You are right, consumer states need to be designed carefully. The current version is the first draft. More work is needed. Also unfortunately our code is not perfect, it needs to be refactored carefully. We need to work iteratively. During state diagram implementation, code refactoring and document update should be done simultaneously.

**Comment by habanoz** [comment]
@jdsika @amzid Please PR needs to be merged before 393. Please merge it if you are happy with the current state.

**Review by jdsika — APPROVED** [review]
@vkresch and @amzid I propose to merge it and modify the diagrams with each layer we work ourselves deeper into the application. Lets keep the "update the diagrams" as a checkpoint for every further FSM PR

**Pull request merged**
