### PR TITLE
Admin/Payout plugin message types

### LINKED ISSUE #327: Separating plugins (telegram, twitter) messages
I set up the Telegram plugin and start receiving all messages in one place like: "Low Payment Address Funds Warning" and "Reward Payouts for Cycle 294 Completed Successfully!". Can we separate official and operational messages, because I don't want to my delegators see unnecessary massages like "Low Payment Address Funds Warning"?

The solution can be:
- configure official and operational messages by chat_ids
- configure turn on/off messages by chat_id

### LINKED ISSUE #334: Why is plugin tag is required in baking config ?
**Describe the bug**
Baking config is not accepted if plugins and enabled tags are not present?

**Expected behavior**
The absence of plugins should be allowed. In this case, no plugin is initialized.

### PR DESCRIPTION
**Pull request by utdrmac**
Close #334 
Close #327 

* **Check list**:

- [x] I extended the Travis CI test units with the corresponding tests for this new feature (if needed).
- [x] I extended the Sphinx documentation (if needed).
- [x] I extended the help section (if needed).
- [x] I changed the README file (if needed).
- [x] I created a new issue if there is further work left to be done (if needed).

**Work effort**: 4hrs

### CODE REVIEW

**Comment by utdrmac** [comment]
Please wait on merge. I'm still testing.

**Comment by utdrmac** [comment]
Ok. Please review. Tested on delphinet and verified Telegram and webhook work. I don't have a twitter to test against but the code remains the same as before.

**Review by habanoz — COMMENTED** [review]
An introductory paragraph on the difference between administrative and payouts notifications would be helpful.

**Review by habanoz — COMMENTED** [review]
https://i.imgur.com/57Lim8s.png

Please note that The title and the first sentence are similar.

**Comment by habanoz** [comment]
@utdrmac Nice work mate. I made two minor comments. Please see them.

**Comment by jdsika** [comment]
@utdrmac resolve conflicts and solve comments. I will merge afterwards

**Comment by utdrmac** [comment]
@jdsika This should be good to go

**Review by jdsika — APPROVED** [review]

**Comment by jdsika** [comment]
@habanoz I have resolved your review remarks. Thank you

**Pull request merged**
