### PR TITLE
Remove fee.ini

### PR DESCRIPTION
**Pull request by denver-s**
---
name: Remove fee.ini
about: Move constants values to batch_payer.py
labels: 

---
IMPORTANT NOTICE:
I read and understood the [guidelines for contributions to the TRD](https://tezos-reward-distributor-organization.github.io/tezos-reward-distributor/contributors.html). The contribution may qualify for being compensated by the TRD grant if approved by the maintainers.

The following steps were performed:

* **Analysis**: As [previously requested](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/pull/448#issuecomment-879752442), file `fee.ini` is now obsolete and its values can be moved to `batch_payer.py`.

* **Performed tests**: `test_simulate_single_operation.py` has been updated.

* **Check list**:

- [x] I extended the Github Actions CI test units with the corresponding tests for this new feature (if needed).
- [x] I extended the Sphinx documentation (if needed).
- [x] I extended the help section (if needed).
- [x] I changed the README file (if needed).
- [x] I created a new issue if there is further work left to be done (if needed).

**Work effort**: 1 hour.

### CODE REVIEW

**Comment by jdsika** [comment]
@denver-s 2 options: move everything into the fee.ini OR remove it and move everything into the header. For the latter you need to check if the fee.ini does exists, warn the user that it is depricated and e.g. rename it!

**Comment by denver-s** [comment]
> @denver-s 2 options: move everything into the fee.ini OR remove it and move everything into the header. For the latter you need to check if the fee.ini does exists, warn the user that it is depricated and e.g. rename it!

I did the latter and I did not check the existence of fee.ini, but it's OK to add it.

What do you mean by "rename it"?

**Comment by jdsika** [comment]
Warning in the log:
"the fee.ini is depricated. You can change the values at XY. Please confirm with yes that the fee.ini will be renamed to fee.ini.old"

Next time the warning will not show up

**Comment by denver-s** [comment]
@jdsika It was difficult to add the check inside the application so I did it inside `main.py`. See https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/commit/4d5cdedb405316634c42a385e3778823a5c9d5d9

**Comment by nicolasochem** [comment]
Instead of a constant in the source code, this should be a [configuration parameter](https://tezos-reward-distributor-organization.github.io/tezos-reward-distributor/configuration.html), shouldn't it?

**Review by jdsika — APPROVED** [review]

**Comment by jdsika** [comment]
I am keeping your comment in #361 to put it in the configuration. If @denver-s has some spare time today you can move it to the configuration with some of the other values like e.g. batch size - if not I will merge this for now

**Comment by denver-s** [comment]
> I am keeping your comment in #361 to put it in the configuration. If @denver-s has some spare time today you can move it to the configuration with some of the other values like e.g. batch size - if not I will merge this for now

As I am not very familiar with all the codebase, I think it's better to open a different PR for this. 

Can we delete this `fee.ini` inside integration tests? https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/blob/master/tests/integration/fee.ini

**Comment by jdsika** [comment]
@denver-s yes I think you have to fix the test as well. If this is fine and you have given your work effort I will merge

**Comment by denver-s** [comment]
@jdsika That fee.ini wasn't even used actually. Tests pass. Work effort added.

**Review by jdsika — APPROVED** [review]

**Pull request merged**
