### PR TITLE
Handle 5XX Errors Better

### LINKED ISSUE #173: Gracefully handle 5XX errors
**Describe the bug**
TRD does not handle 5XX errors from http RPC endpoints well.

**To Reproduce**
Use a public RPC endpoint that is currently down/offline but still returns 522 or 524. As of right now, https://rpc.tulip.tools/mainnet/chains/main/blocks/head, is returning CloudFlare 522 errors.

**Expected behavior**
A proper error message be displayed, not a stack-trace/Exception

```
Traceback (most recent call last):
  File "src/pay/payment_producer.py", line 225, in try_to_pay
    reward_model = self.reward_api.get_rewards_for_cycle_map(pymnt_cycle)
  File "src/rpc/rpc_reward_api.py", line 45, in get_rewards_for_cycle_map
    current_level, current_cycle = self.__get_current_level()
  File "src/rpc/rpc_reward_api.py", line 123, in __get_current_level
    def __get_current_level(self):
  File "src/rpc/rpc_reward_api.py", line 115, in do_rpc_request
    if resp.status_code != 200:
Exception: Request 'https://rpc.tulip.tools/mainnet//chains/main/blocks/head failed with status code 524
```

### PR DESCRIPTION
**Pull request by utdrmac**
Resolves #173
* Switch a few exception messages to errors and add another try-catch
* This was mostly solved via earlier PRs

[NA] I extended the Travis CI test units with the corresponding tests for this new feature (if needed).
[NA] I extended the Sphinx documentation (if needed).
[NA] I extended the help section (if needed).
[NA] I changed the README file (if needed).
[NA] I created a new issue if there is further work left to be done (if needed).

**Work effort**: 1hr

### CODE REVIEW

**Comment by jdsika** [comment]
@habanoz please approve if it looks good to you. I handed it to you as it concerns "logging"

**Review by habanoz — APPROVED** [review]
1 merge conflict resolved.

**Comment by jdsika** [comment]
@habanoz not building, please fix and approve for me to merge

**Comment by habanoz** [comment]
@jdsika Please proceed.

**Pull request merged**
