### PR TITLE
disable RPC after Mumbai

### PR DESCRIPTION
**Pull request by nicolasochem**
There are 2 problems:

* blocks per cycle is changing, so the calculation of cycle beginning, cycle snapshots etc... needs to be adjusted
* due to twice more blocks per cycle, the rights query will take even longer, making rpc provider even less appealing as an option

Besides, the engineering capacity is limited, and everyone is using TRD with tzkt. Let's disable RPC for now.

Effort: nicolasochem, 0.5h | jdsika, 0.5h

### CODE REVIEW

**Comment by jdsika** [comment]
tzstats is working to my knowledge. Was it disabled before?

**Comment by nicolasochem** [comment]
> tzstats is working to my knowledge. Was it disabled before?

I guess so. I found the code like this :)

**Comment by jdsika** [comment]
Well. I just figured out that the whole thing is not working, great

**Comment by jdsika** [comment]
I am fixing it

**Review by jdsika — APPROVED** [review]

**Comment by vkresch** [comment]
There are currently tests which are stuck in an infinite loop on the CI but locally they are fine. I am currently disabling them. Will merge them shortly into master.

**Pull request merged**
