### PR TITLE
Updated plugin support for tweepy v4

### LINKED ISSUE #517: Error Details: 'API' object has no attribute 'me'
**Describe the bug**
When starting TRD get Error Details: 'API' object has no attribute 'me'

**To Reproduce**
1. Start TRD
2. See error:
2021-12-07 14:25:44,144 - MainThread - INFO - --------------------------------------------
2021-12-07 14:25:44,145 - MainThread - INFO - [Plugins] Loaded plugin Telegram
2021-12-07 14:25:44,160 - MainThread - **ERROR - [Process Life Cycle completing With Failure] Error Details: 'API' object has no attribute 'me'**
2021-12-07 14:25:44,160 - MainThread - INFO - TRD is shutting down...
2021-12-07 14:25:44,160 - MainThread - INFO - --------------------------------------------------------
2021-12-07 14:25:44,160 - MainThread - INFO - Sensitive operations are in progress!
2021-12-07 14:25:44,161 - MainThread - INFO - Please wait while the application is being shut down!
2021-12-07 14:25:44,161 - MainThread - INFO - -------------------------------------------------------

**Environment**
 - Source Code Build
 - Chain mainnet
 - python3 src/main.py -D -C 423 -M 3
 - Ubuntu 20.04.3 LTS

### PR DESCRIPTION
**Pull request by ericlavoie**
Updated plugin support for tweepy v4.
Version 4 made many non compatible changes, including the call we make to connecty and get username or the twitter account.

---
name: Updated plugin support for tweepy v4
about: Version 4 made many non compatible changes, including the call we make to connecty and get username or the twitter account.
labels: 

---
IMPORTANT NOTICE:
I read and understood the [guidelines for contributions to the TRD](https://tezos-reward-distributor-organization.github.io/tezos-reward-distributor/contributors.html). The contribution may qualify for being compensated by the TRD grant if approved by the maintainers.

This PR resolves #517. The following steps were performed:

* **Analysis**: Ran the code with Tweepy version 4, the same error as specified occurred.

* **Solution**: In the twitter.py module, change the call to the new API method if it is version 4, and the old call if it's older than version 4 (3 and lower)

* **Implementation**: Pulled the version from the module, extracted the major version from the returned info, compared majorversion if it is lower than 4, call the older method, and elsed it to the new method, cannot assume this will only be for version 4, this why I used the else condition, it will support 4 and up.
* 
* * **Performed tests**: Ran it in my environment, it loaded the module with no error.

* **Documentation**: No changes were needed to the docuemntation.
* 
* **Check list**:

- [ ] I extended the Github Actions CI test units with the corresponding tests for this new feature (if needed).
- [ ] I extended the Sphinx documentation (if needed).
- [ ] I extended the help section (if needed).
- [ x ] I changed the README file (if needed).
- [ ] I created a new issue if there is further work left to be done (if needed).

**Work effort**: 1h

### CODE REVIEW

**Comment by ericlavoie** [comment]
It looks like I made a contribution also to fix the twitter plugin for tweepy v4

**Comment by jdsika** [comment]
Can you revert the changes to the test network URLs and only submit the twitter plugin fix? I had to do the update on the pipiline in another PR as it was quite complicated and needed to be merged first. Thanks :)

**Comment by ericlavoie** [comment]
> Can you revert the changes to the test network URLs and only submit the twitter plugin fix? I had to do the update on the pipiline in another PR as it was quite complicated and needed to be merged first. Thanks :)

I checked the difference, 

> Can you revert the changes to the test network URLs and only submit the twitter plugin fix? I had to do the update on the pipiline in another PR as it was quite complicated and needed to be merged first. Thanks :)

The merge yo approved, changes how the code worked, it sets the testnet for one at giganode, versus smartpy.io previous value.
CURRENT_TESTNET: 'https://hangzhou.smartpy.io'
I suggest you resolve the conflicting files to your choice, my changes are inline to the previous setup. I am not at ease in reverting a commit. I can try, no guarantees.

**Comment by ericlavoie** [comment]
OK I reverted the commits.

**Review by jdsika — DISMISSED** [review]

**Review by jdsika — APPROVED** [review]

**Pull request merged**
