### PR TITLE
Rework exceptions for payment producer loop

### PR DESCRIPTION
**Pull request by utdrmac**
This PR resolves some issues mentioned in #291.

[NA] I extended the Travis CI test units with the corresponding tests for this new feature (if needed).
[NA] I extended the Sphinx documentation (if needed).
[NA] I extended the help section (if needed).
[NA] I changed the README file (if needed).
[NA] I created a new issue if there is further work left to be done (if needed).

**Work effort**: 1hr

### CODE REVIEW

**Comment by utdrmac** [comment]
Resolves #291

**Comment by jdsika** [comment]
Changed reviewer from @amzid to @habanoz !

**Comment by jdsika** [comment]
@utdrmac I am leaning toward releasing a quick v8.1 including the bug fix. What do you think?

**Comment by utdrmac** [comment]
I'm good with 8.1

**Comment by amzid** [comment]
I am getting the following error now:
`2020-11-22 12:48:32,401 - producer  - Unknown error in payment producer loop: unsupported format string passed to dict.__format__
Traceback (most recent call last):
  File "/home/it-test/tezos-reward-distributor/src/pay/payment_producer.py", line 194, in run
    result = self.try_to_pay(pymnt_cycle)
  File "/home/it-test/tezos-reward-distributor/src/pay/payment_producer.py", line 302, in try_to_pay
    raise e from e
  File "/home/it-test/tezos-reward-distributor/src/pay/payment_producer.py", line 266, in try_to_pay
    reward_model = self.reward_api.get_rewards_for_cycle_map(pymnt_cycle)
  File "/home/it-test/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 78, in get_rewards_for_cycle_map
    raise e from e
  File "/home/it-test/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 40, in get_rewards_for_cycle_map
    current_level, current_cycle = self.__get_current_level()
  File "/home/it-test/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 212, in __get_current_level
    head = self.do_rpc_request(COMM_HEAD.format(self.node_url))
  File "/home/it-test/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 143, in do_rpc_request
    logger.debug("[do_rpc_request] Response {:s}".format(response))
TypeError: unsupported format string passed to dict.__format__`

**Review by amzid — APPROVED** [review]

**Pull request merged**
