### PR TITLE
Add TRD support for Dexter liquidity pool payouts (tzstats)

### PR DESCRIPTION
**Pull request by amzid**
This PR solves partially #276. Following steps were performed:
- Get in touch with CamlCase for clarification about Dexter integration.
- Feature request for TzKt/BCD to implement needed end points (big maps)
- Implementation based on Tzstats because of their good support for big map queries at any block.
- Extension of baking configuration (Dexter contracts configurable)
- Partial implementation for rpc support
- Compare results with latest payouts performed for Dexter-based contracts (USDtz, tzBTC)

Work effort: 41 hrs

### CODE REVIEW

**Comment by jdsika** [comment]
Is the program telling the user that - when the contract is enabled through the config - it cannot be done without explicitly using tzstats as backend and handling it gracefully?

**Comment by amzid** [comment]
> Is the program telling the user that - when the contract is enabled through the config - it cannot be done without explicitly using tzstats as backend and handling it gracefully?

Yes, if the provider is different from tzstats then the following message is displayed at the beginning: `The Dexter funktionality is currently supported only using tzstats.The contract address will be treated as a normal delegator.`

**Comment by utdrmac** [comment]
I see lots of deep changes into payments_producer and rewards_api. I don't know anything about Dexter so maybe these changes are needed to support. Just my cautionary $0.02.

**Comment by amzid** [comment]
> I see lots of deep changes into payments_producer and rewards_api. I don't know anything about Dexter so maybe these changes are needed to support. Just my cautionary $0.02.

Another data structure is added to store a set of delegator contracts which have the form of a Dexter contract. The contract stores a list of so-called liquidity providers which have an amount of a specific token (USDtz or tzBTC for example, more tokens can be added in the future).
- If the set of dexter contracts is not empty and tzstats is set as provider, the equivalent of the token amounts (queried from the big map associated to the contract storage) is added to the staking balance of the delegator. 
- If the set of dexter contracts is empty or tzstats is not set as provider, no changes will be performed to the old reward model.

**Comment by dansan566** [comment]
```
Traceback (most recent call last):
  File "src/main.py", line 10, in <module>
    from api.provider_factory import ProviderFactory
  File "/Users/danielliebert/tezos-reward-distributor/src/api/provider_factory.py", line 2, in <module>
    from rpc.rpc_reward_api import RpcRewardApiImpl
  File "/Users/danielliebert/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 8, in <module>
    from Dexter import dexter_utils as dxtz
  File "/Users/danielliebert/tezos-reward-distributor/src/Dexter/dexter_utils.py", line 3, in <module>
    from parse import parse
ModuleNotFoundError: No module named 'parse'
```

**Comment by jdsika** [comment]
Frozen payouts do work now with tzKT. Reminder to not forget to mention it in the merge

**Comment by dansan566** [comment]
- [X] tested with RPC/PRPC/tzstats and tzkt for normal functionality 
- [X] tested with tzstats for dexter liquidity pool functionality

**Comment by jdsika** [comment]
@dansan566 please state your review effort in hours

**Comment by dansan566** [comment]
- [X] Also tested the frozen payout with tzkt `python3 src/main.py -C 291 -R -1 -P tzkt -M 3 -V -D` -> worked

**Review by jdsika — APPROVED** [review]

**Pull request merged**
