### PR TITLE
Missing api_base_url parameter in retry_failed.py

### LINKED ISSUE #253: retryfailed failed - AttributeError: 'Namespace' object has no attribute 'api_base_url'
**Describe the bug**
retry_failed.py doesn't run
AttributeError: 'Namespace' object has no attribute 'api_base_url'

**To Reproduce**
have a failed batch.
run retry_failed.py

**Expected behavior**
work

**Screenshots**
python3 src/retry_failed.py
```
 _____ ______ ______
|_   _|| ___ \|  _  \
  | |  | |_/ /| | | |
  | |  |    / | | | |
  | |  | |\ \ | |/ /
  \_/  \_| \_||___/

--------------------------------------------
Copyright Huseyin ABANOZ 2019
huseyinabanox@gmail.com
Please leave copyright information
--------------------------------------------
2020-08-28 19:39:20,887 - MainThread - Tezos Reward Distributor - Retry Failed Files is Starting
2020-08-28 19:39:20,888 - MainThread - Arguments Configuration = {
 "network": "MAINNET",
 "reward_data_provider": "prpc",
 "reports_base": "~/pymnt/reports",
 "config_dir": "~/pymnt/cfg",
 "node_addr": "http://127.0.0.1:8732",
 "dry_run": false,
 "dry_run_no_consumers": false,
 "executable_dirs": "~/,~/tezos",
 "docker": false,
 "verbose": false,
 "retry_injected": false
}
2020-08-28 19:39:20,888 - MainThread - master configuration file not present.
2020-08-28 19:39:20,952 - MainThread - Loading baking configuration file /home/leo/pymnt/cfg/tz1NEKxGEHsFufk87CVZcrqWu8o22qh46GK6.yaml
Traceback (most recent call last):
  File "src/retry_failed.py", line 208, in <module>
    main(args)
  File "src/retry_failed.py", line 96, in main
    network_config, args.node_addr, api_base_url=args.api_base_url)
AttributeError: 'Namespace' object has no attribute 'api_base_url'
```
**Environment**
 - Source Code Build 
 - Chain mainnet, 
 - actual command used
python3 src/retry_failed.py
**Additional context**
have the latest code

### PR DESCRIPTION
**Pull request by utdrmac**
Closes #253 

This PR resolves the issue #253 . The following steps were performed:

* **Analysis**: CLI parameters that were added in #232 were missing from retry_failed.py
* **Solution**: Added missing parameters
* **Implementation**: ^^
* **Performed tests**: Tested/confirmed by end-user songproducer in issue
* **Documentation**: NA
* **Check list**:

[NA] I extended the Travis CI test units with the corresponding tests for this new feature (if needed).
[NA] I extended the Sphinx documentation (if needed).
[NA] I extended the help section (if needed).
[NA] I changed the README file (if needed).
[NA] I created a new issue if there is further work left to be done (if needed).

**Work effort**: 2hrs

### CODE REVIEW

**Comment by utdrmac** [comment]
ugh. crap. i committed something for another issue.

**Comment by jdsika** [comment]
Time effort is missing + the usage of the PR template. Could you edit it please? 
We need @amzid for a review before we merge.

**Review by amzid — APPROVED** [review]
We might need to think about a better way in the future to avoid adapting retry_failed.py each time we mak a change to main.py by trying somehow to merge both files or putting the common relevant parts in callable functions.

**Comment by utdrmac** [comment]
Agreed. I think we should be able to remove retry_failed.py completely and integrate another `-M` mode for this purpose. It's 99% the same code as main.py + everything else.

**Comment by jdsika** [comment]
Please do not forget to document the work effort + contributor github name in the squash commit into master

**Pull request merged**
