### PR TITLE
Release v11

### PR DESCRIPTION
**Pull request by jdsika**
General:

- [x] Transaction Documentation
- [x] Release Notes
- [x] Make green tests and fix bugs
- [x] Add failsafe to avoid usage after 31.03.2023
- [x] Missing transactions from #579 

Contributor | Sum hours | $ / hour | $ | VWAP XTZUSD | XTZ |  hash
-- | -- | -- | -- | -- | -- | -- 
@AndrewKishino | 2 | 70 | 140 | 0.798013 | 175.435738515538 | [link](https://tzkt.io/op7A1m2HQkuD6ZtZAJW1SJRZ4eSgJ7X9jEqZGk3qipHStL3CzNK/4188689)
@NeoktaLabs | 1 | 70 | 70 | 0.798013 | 87.717869257769 | [link](https://tzkt.io/ooSgxukNtaLD6eGqYYenmdQZMm1aEg4QeEyAsvBef3FE5j6YJaL/4188692)
@redref | 1 | 70 | 70 | 0.798013 | 87.717869257769 | [link](https://tzkt.io/oo893vTeAV5HiWLdLcuWCrJ2S2iXEyyE92TitVYmZ4fRr7UT45Y/4188693)
@sebuhbitcoin | 1 | 70 | 70 | 0.798013 | 87.717869257769 | [link](https://tzkt.io/op6p7kfHm32p6BTDPhCxm8gKNVTu6ZbqQhxSD64bF3St5egceNP/4188694)
@Vlad1mir-D | 12 | 70 | 840 | 0.798013 | 1052.61443109323 | --
@jdsika  | 19.25 | 70 | 1347.5 | 0.798013 | 1688.56898321205 | --
@rvermootenct   | 18.6 | 70 | 1302 | 0.798013 | 1631.5523681945 | --
@nicolasochem    | 30.5 | 70 | 2135 | 0.798013 | 2675.39501236195 | --
@vkresch     | 32 | 70 | 2240 | 0.798013 | 2806.97181624861 | [link](https://tzkt.io/ooqAoss9bnRh9FK27SaCpj6yeYqTwgLWamnBeWK6jhc7vFAZTa3/4188695)
@novalis     | 5 | 70 | 350 | 0.798013 | 438.589346288845 | --
@pea-io      | 4.25 | 70 | 297.5 | 0.798013 | 372.800944345518 | [link](https://tzkt.io/ooMT6orgp1KG1yCajT1a5TwLxnZ7epXVWh9vz3QAobRMTTfSe8j/4188696)
| - | - | - | -| - | 11105.0822480336 | TOTAL

@utdrmac the current balance is only 7910 tez [link](https://tzkt.io/KT1Hir1o22RGE1Hyrrzpp3rXjhTcoUurSYKu/operations/). I propose to not pay myself and @nicolasochem . After the grant milestone is fulfilled with this release we can add the payments for end of January.

Effort=4h

### CODE REVIEW

**Comment by jdsika** [comment]
@Vlad1mir-D you need to add your tz address for us to make the payments quickly, please

**Comment by jdsika** [comment]
@rvermootenct please add your tz address quickly

**Comment by utdrmac** [comment]
@novalis Missing your payout address too

**Review by dansan566 — APPROVED** [review]

**Comment by novalis** [comment]
Please use tz2A7R79sETkLMPsHX5Cws686mqBHH8tKBmQ for my xtz.  Thanks.

**Comment by Vlad1mir-D** [comment]
> @Vlad1mir-D you need to add your tz address for us to make the payments quickly, please

Didn't realize that this funding is for all contributors involved in the development, not some selected.
[Here is it](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/pull/647).
Thanks!

**Comment by jdsika** [comment]
Funding is for everyone who contributes and is not payed by any other entity at the same time. See guidelines for this. @novalis please do your own PR as every contributor should add his own address. It reduces the risk of fraud and wrong payments. thanks!

**Comment by novalis** [comment]
In that case, count me out -- I was paid by Oxhead Alpha for this work, and I don't anticipate doing further work.

**Comment by Vlad1mir-D** [comment]
> Funding is for everyone who contributes and is not payed by any other entity at the same time. See guidelines for this. 

I'm paid by other entity, so count me out too.

**Pull request merged**
