### PR TITLE
Improved Documentation for v9 

### PR DESCRIPTION
**Pull request by dansan566**
---
name: Pull Request
about: Create a pull request to make a contribution
labels: documentation & logging

---
IMPORTANT NOTICE:
I read and understood the [guidelines for contributions to the TRD](https://tezos-reward-distributor-organization.github.io/tezos-reward-distributor/contributors.html). The contribution may qualify for being compensated by the TRD grant if approved by the maintainers.

This PR resolves the issue #324. The following steps were performed:

* **Analysis**: The documentation is outdated and needs a complete revision. 

* **Solution**: Change the RST files

* **Check list**:

- [ ] I extended the Travis CI test units with the corresponding tests for this new feature (if needed).
- [x] I extended the Sphinx documentation (if needed).
- [ ] I extended the help section (if needed).
- [ ] I changed the README file (if needed).
- [ ] I created a new issue if there is further work left to be done (if needed).

**Work effort**: 10h

### CODE REVIEW

**Comment by dansan566** [comment]
@amzid wondering why commit hash 8f4c854411f7eb73e0c27e6a3297520769a04c30 is included...

**Comment by jdsika** [comment]
@dansan566 please remove [WIP] when your contribution is ready for review. @amzid will add the docker section with #229

**Comment by dansan566** [comment]
@jdsika I think it is not ready for a review. Looking for help @amzid (Tezos Signer, Tezos Signer with Docker, Payment Address).

**Comment by amzid** [comment]
The discussed parts were adjusted. tezossignerdocker.rst will be adjusted after #229 is ready.

**Comment by jdsika** [comment]
@dansan566 ready to merge?

**Review by jdsika — APPROVED** [review]
LGTM

**Pull request merged**
