### PR TITLE
Parse and check result of run_operation

### LINKED ISSUE #244: Check return value of run_operation before injecting
Right now TRD executes the RPC run_operation but does not check the result for possible errors. It should.

### PR DESCRIPTION
**Pull request by utdrmac**
Closes #244

### CODE REVIEW

**Comment by utdrmac** [comment]
Effort Time: 3 hours

**Review by amzid — APPROVED** [review]
Thanks for the PR. This is a great contribution. Now, the payment fails already at the simulation phase when the balance is too low for example, returns a warning, and does not proceed to the forging and injection steps.

**Comment by jdsika** [comment]
@habanoz 
I think this should be the first candidate for a merge including the transaction hash of the grant payment.

**Comment by utdrmac** [comment]
> Thanks for the PR. This is a great contribution. Now, the payment fails already at the simulation phase when the balance is too low for example, returns a warning, and does not proceed to the forging and injection steps.

Exactly! Should help make things a bit more clearer to users. And there was one guy, @gaia IIRC, who wanted to see the balance beforehand so he could transfer to his payouts address. This should address that in a roundabout way.

**Comment by jdsika** [comment]
@amzid please evaluate if this resolves #116 , #149 and #220

**Comment by jdsika** [comment]
Review and checking: amzid, effort=0,5h

**Pull request merged**
